//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uspa.Domain.LocalDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories()
        {
            this.Contents = new HashSet<Contents>();
            this.IdentityRoles = new HashSet<IdentityRoles>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public int previd { get; set; }
        public Nullable<System.DateTime> createdTime { get; set; }
        public bool published { get; set; }
        public string createdByUser_Id { get; set; }
        public Nullable<int> language_id { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contents> Contents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdentityRoles> IdentityRoles { get; set; }
    }
}
