//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uspa.Domain.LocalDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contents()
        {
            this.Menus = new HashSet<Menus>();
        }
    
        public int id { get; set; }
        public int previd { get; set; }
        public string title { get; set; }
        public string introtext { get; set; }
        public string fulltext { get; set; }
        public bool state { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<System.DateTime> published { get; set; }
        public Nullable<System.DateTime> checkIn { get; set; }
        public Nullable<System.DateTime> checkOut { get; set; }
        public Nullable<int> category_id { get; set; }
        public string createdByUser_Id { get; set; }
        public string modifiedByUser_Id { get; set; }
        public Nullable<int> site_id { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Sites Sites { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menus> Menus { get; set; }
    }
}
