//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uspa.Domain.LocalDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public long id { get; set; }
        public string title { get; set; }
        public string filePath { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public bool state { get; set; }
        public Nullable<int> album_id { get; set; }
        public string createdByUser_Id { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual Users Users { get; set; }
    }
}
