//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uspa.Domain.LocalDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int id { get; set; }
        public int previd { get; set; }
        public Nullable<int> parentidPrev { get; set; }
        public Nullable<int> parentid { get; set; }
        public string title { get; set; }
        public bool state { get; set; }
        public Nullable<long> menuType_id { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> сontent_id { get; set; }
    
        public virtual Contents Contents { get; set; }
        public virtual MenuTypes MenuTypes { get; set; }
        public virtual Sites Sites { get; set; }
    }
}
